### ISSUE TITLE
Problem with UPDATE on DATE primary key (part) in MySQL

### ISSUE THREAD

**Issue by jkavalik** [nextras/orm#320]
Currently when any date/time column is used in the DB, it is mapped to a DateTimeImmutable. When such column is in the primary key, it is [being formatted](https://github.com/nextras/orm/blob/master/src/Entity/AbstractEntity.php#L389) including the timezone specification. I have a problem with MariaDB where the updates are not happening, because [the incorrectly formatted value is silently ignored](https://jira.mariadb.org/browse/MDEV-17656). In MySQL such situation is even supposed to throw an error instead, which I was able to simulate by dropping the primary key from the table, which triggers the same error in MariaDB.
![tracy_date_error](https://user-images.githubusercontent.com/5812825/48268957-b886a980-e436-11e8-8b98-8e0f2c2fc0e3.png)

Selects work and can find the row, but they throw a warning anyway.

Would it be somehow possible to format the datetime for current platform? It is currently done in AbstractEntity where I am not sure such information would be available, and the string is needed for identity map functioning properly. But maybe the identity map could format it any way it wants to ensure proper indexing and the Mapper could use the Platform to format it properly?

**Comment by hrach** [comment]
Hi, I do not understand the problem fully (where the bug actually is). The easiest way to force the Dbal to format this without timezone is to change modifier to `%dts`. You may do this by changing it in Mapper, [see doc](https://github.com/nextras/orm/blob/master/src/Mapper/Dbal/StorageReflection/StorageReflection.php).

**Comment by jkavalik** [comment]
Probably I am just missing something obvious :) 
When I update the entity and persist the changes, ORM generates an UPDATE statement as `UPDATE doc_calendars SET available = 1 WHERE date = '2018-11-09T00:00:00+01:00.000000' AND time = '15:45:00' AND office_i` = 1;`
I see no way how to change the '2018-11-09T00:00:00+01:00.000000' to '2018-11-09T00:00:00' as the WHERE is generated automatically from the Primary key, and no modifiers are used in that process as far as I can see.

**Comment by hrach** [comment]
Oh, I see it! This is a huge bug! Will try a fix it today.

**Comment by hrach** [comment]
Hi, I've prepared fix in #322. The changes are sadly quite bigger and with little BC so I do not want to pull this for 3.0.x release. 3.1 should be released pretty soon. If you could test it, it would be great :)

**Comment by jkavalik** [comment]
Hi, testing. The datetime in composite key seems to work fine now, but I found some problems in the case when the date(time) column is THE primary key, no composite:
getIdHash() will try to convert the DateTimeImmutable to a string because it is not an array
AbstractEntity::setterPrimaryProxy() `$value = (array) $value;` will convert the one DateTimeImmutable object to an array of 3 items:
```
object(DateTimeImmutable)#132 (3) {
     ["date"]=>
     string(26) "2019-01-01 00:00:00.000000"
     ["timezone_type"]=>
     int(3)
     ["timezone"]=>
     string(13) "Europe/Prague"
   }
=>
array(3) {
     ["date"]=>
     string(26) "2019-01-01 00:00:00.000000"
     ["timezone_type"]=>
     int(3)
     ["timezone"]=>
     string(13) "Europe/Prague"
   }

and the same happens in DbalMapper::persist() - `$id = (array) $entity->getPersistedId();`

**Comment by hrach** [comment]
Oh, I see, quite easy to fix. Will do in the evening.

**Comment by hrach** [comment]
I have updated the PR.

**Comment by jkavalik** [comment]
I see the updated getIdHash() but still getting "Value for NextrasTests\Orm\UserStatX::$id has insufficient number of parameters." for the case when the DATETIME is the (single-column) PK.

**Comment by hrach** [comment]
:( I will do better next time. That's because I didn't write a test... :( Will do it and fix it properly. Sorry.

**Comment by jkavalik** [comment]
No problem :) I just was not sure if maybe I missed some part.
